WeatherWebApp/Controllers/WeatherController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using NPOI.OpenXml4Net.Exceptions;
using WeatherWebApp.Models;
using WeatherWebApp.Common;
using WeatherWebApp.Common.Serialization;

namespace WeatherWebApp.Controllers
{
    public class WeatherController : Controller
    {
        private const int DefaultPageSize = 5;

        private readonly WeatherDbContext dbContext;
        private readonly int pageSize;

        public WeatherController(WeatherDbContext dbContext, IConfiguration configuration)
        {
            this.dbContext = dbContext;

            if (!int.TryParse(configuration["ViewSettings:ItemsPerPage"], out pageSize) || pageSize < 1)
            {
                pageSize = DefaultPageSize;
            }
        }

        [Route("Weather/Yearly/{Page?}")]
        public IActionResult Yearly(int page = 1)
        {
            IEnumerable<WeatherViewModel> averageWeather =
                dbContext.Weather
                .AsNoTracking()
                .AverageDataForGroupByYears()
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            return View("Index", 
                new WeatherListViewModel()
                {
                    PagingInfo = new PagingInfo()
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSize,
                        TotalItems = dbContext.Weather
                            .Select(w => w.DateTime.Year)
                            .Distinct()
                            .Count()
                    },
                    WeatherList = averageWeather
                });
        }

        [Route("Weather/Monthly/{Page?}")]
        public IActionResult Monthly(int page = 1)
        {
            IEnumerable<WeatherViewModel> averageWeather =
                dbContext.Weather
                    .AsNoTracking()
                    .AverageDataForGroupByMonths()
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize);

            return View("Index",
                new WeatherListViewModel()
                {
                    PagingInfo = new PagingInfo()
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSize,
                        TotalItems = dbContext.Weather
                            .Select(w => new { w.DateTime.Year, w.DateTime.Month })
                            .Distinct()
                            .Count()
                    },
                    WeatherList = averageWeather
                });
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile[] files)
        {
            if (files.Length == 0)
            {
                return View(nameof(Upload), new FileUploadViewModel() { IsSuccessful = false, Message = "Не был загружен ни один файл" });
            }

            string currentFileName = string.Empty;
            try
            {
                foreach (IFormFile file in files)
                {
                    currentFileName = file.FileName;
                    await using (Stream fileStream = file.OpenReadStream())
                    {
                        IEnumerable<Weather> fileData = ExcelSerializer.DeserializeExcel(fileStream);
                        await dbContext.AddRangeAsync(fileData);
                    }
                }
            }
            catch (InvalidFormatException)
            {
                return View(nameof(Upload), new FileUploadViewModel() { IsSuccessful = false, Message = $"Загруженный файл {currentFileName} имеет неправильный формат" });
            }

            await dbContext.SaveChangesAsync();
            return View(nameof(Upload), new FileUploadViewModel() { IsSuccessful = true, Message = "Данные успешно загружены в базу данных" });
        }

    }
}

WeatherWebApp/Views/Shared/UploadAlert.cshtml
@model FileUploadViewModel

<div class="alert @(Model.IsSuccessful ? "alert-success" : "alert-danger") m-4" role="alert">
    <h4 class="alert-heading"> @(Model.IsSuccessful ? "Загрузка прошла успешно" : "При загрузке произошла ошибка")</h4>
    <p>@Model.Message</p>
</div>

WeatherWebApp/Views/Shared/WeatherCard.cshtml
@using System.Globalization
@model WeatherViewModel

<div class="card m-2" style="width: 100%;">
    <div class="card-header">
        @if (Model.Month.HasValue)
        {
            @(new DateTime(1, Model.Month.Value, 1).ToString("MMMM ", new CultureInfo("ru-RU")))
        }
        @Model.Year г.
    </div>
    <div class="card-body" style="display: flex; flex-direction: row;">
        <ul class="list-group">
            <li class="list-group-item border-light">Температура: @Model.Temperature.ToString("0")°C</li>
            <li class="list-group-item border-light">Относительная влажность: @Model.Humidity.ToString("0")%</li>
            <li class="list-group-item border-light">Точка росы: @Model.DewPoint.ToString("F1") гр.</li>
            <li class="list-group-item border-light">Давление: @Model.Temperature.ToString("0") мм рт. ст.</li>
            <li class="list-group-item border-light">Направление ветра: @Model.WindDirection</li>
        </ul>
        <ul class="list-group">
            <li class="list-group-item border-light">Скорость ветра: @Model.WindSpeed.ToString("0") м/с</li>
            <li class="list-group-item border-light">Облачность: @Model.Cloudiness.ToString("0")%</li>
            <li class="list-group-item border-light">Нижняя граница облачности: @Model.CloudBase.ToString("0") м</li>
            <li class="list-group-item border-light">Видимость: @Model.HorizontalVisibility.ToString("0") км</li>
            <li class="list-group-item border-light">Погодные условия: @Model.WeatherConditions</li>
        </ul>
    </div>
</div>

WeatherWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <script src="/lib/bootstrap/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="/lib/bootstrap/css/bootstrap.min.css" type="text/css" rel="stylesheet"/>
    <title>WeatherApp</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Погодные условия</a>
            <div class="navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
                            Архив
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Weather" asp-action="Monthly">Ежемесячные данные</a></li>
                            <li><a class="dropdown-item" asp-controller="Weather" asp-action="Yearly">Ежегодные данные</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Weather" asp-action="Upload">Загрузить</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
</body>
</html>